POST http://localhost:8080/events
Content-Type: application/json  

{
	"Name" :       "Birthday Party 2026",
	"Description": "Celebrating John's birthday",
	"Location" :   "123 Main Street",
	"Date"   :     "2026-01-15T18:00:00Z"
}