PUT http://localhost:8080/events/1
Content-Type: application/json  

{
	"Name" :       "Birthday 4544 2026",
	"Description": "6455464 John's birthday",
	"Location" :   "123 Mai64564564n Street",
	"Date"   :     "2026-01-15T18:00:00Z"
}